// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanosSaude.API.Data;

#nullable disable

namespace PlanosSaude.API.Migrations
{
    [DbContext(typeof(PlanosSaudeDbContext))]
    [Migration("20260227105225_Migration001")]
    partial class Migration001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlanosSaude.API.Models.Beneficiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("beneficiarios", (string)null);
                });

            modelBuilder.Entity("PlanosSaude.API.Models.Contratacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BeneficiarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiario_id");

                    b.Property<DateTimeOffset?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTimeOffset>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiarioId");

                    b.HasIndex("PlanoId");

                    b.ToTable("contratacoes", (string)null);
                });

            modelBuilder.Entity("PlanosSaude.API.Models.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cobertura")
                        .HasColumnType("integer")
                        .HasColumnName("cobertura");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<decimal>("CustoMensal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("custo_mensal");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("planos", (string)null);
                });

            modelBuilder.Entity("PlanosSaude.API.Models.Contratacao", b =>
                {
                    b.HasOne("PlanosSaude.API.Models.Beneficiario", "Beneficiario")
                        .WithMany("Contratacoes")
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlanosSaude.API.Models.Plano", "Plano")
                        .WithMany("Contratacoes")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beneficiario");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("PlanosSaude.API.Models.Beneficiario", b =>
                {
                    b.Navigation("Contratacoes");
                });

            modelBuilder.Entity("PlanosSaude.API.Models.Plano", b =>
                {
                    b.Navigation("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
